OTP_EXPIRE_MINUTES = 5
OTP_MAX_ATTEMPTS = 5
OTP_RESEND_COOLDOWN_SECONDS = 60

MAX_RECIPIENTS_PER_BROADCAST = 10
BROADCAST_MIN_INTERVAL_SECONDS = 60
INTER_MESSAGE_DELAY_SECONDS = 2

MAX_MEDIA_SIZE_BYTES = 10 * 1024 * 1024
ALLOWED_MEDIA_CONTENT_TYPES = {"image/jpeg", "image/png", "image/webp", "image/gif"}
